# Generated by Django 5.1.6 on 2025-03-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('date', models.DateField(unique=True)),
                ('time', models.TimeField()),
                ('address', models.TextField()),
                ('program', models.CharField(max_length=200)),
            ],
        ),
    ]
