# Generated by Django 5.1.6 on 2025-03-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
